openapi: 3.0.1
info:
  title: Swagger Balancer
  description: "This is a sample server Petstore server.  You can find out more about\
    \     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,\
    \ #swagger](http://swagger.io/irc/).      For this sample, you can use the api\
    \ key `special-key` to test the authorization     filters."
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://petstore.swagger.io/v2
- url: http://petstore.swagger.io/v2
tags:
- name: summ
  description: Summ 2 numbers
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /summ:
    get:
      tags:
      - summ
      summary: Get previous results
      description: Multiple status values can be provided with comma separated strings
      operationId: get_results
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Results'
                x-content-type: application/json
        "400":
          description: Invalid status value
          content: {}
      x-swagger-router-controller: swagger_server.controllers.summ_controller
      x-openapi-router-controller: swagger_server.controllers.summ_controller
    post:
      tags:
      - summ
      summary: summ 2 numbers
      operationId: summ2_nums
      requestBody:
        description: 2 numbers to operate with
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nums'
        required: true
      responses:
        "405":
          description: Invalid input
          content: {}
      x-swagger-router-controller: swagger_server.controllers.summ_controller
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.summ_controller
components:
  schemas:
    Nums:
      type: object
      properties:
        num1:
          type: number
          format: double
          example: 12.0
        num2:
          type: number
          format: double
          example: 1.0
        operation:
          type: string
          description: Types of operations
          example: add
          enum:
          - '*'
          - +
          - "-"
      example:
        num1: 12
        operation: add
        num2: 1
      xml:
        name: Nums
    Results:
      type: object
      properties:
        result:
          type: number
          format: double
          example: 13.0
        input:
          type: string
          example: 12+1
      example:
        result: 13
        input: 12+1
x-original-swagger-version: "2.0"

