openapi: 3.0.0
info:
  description: >-
    This is a sample server python-flask.
  version: 1.0.0-oas3
  title: "Number Operator"
  contact:
    email: prokhorov.va@phystech.edu
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:8080/server/'
    
tags:
  - name: summ
    description: 'Summ 2 numbers'
    externalDocs:
      description: 'Find out more'
      url: 'http://swagger.io'
paths:
  /operate:
    post:
      tags:
        - summ
      summary: 'operate 2 numbers'
      description: ''
      operationId: doAction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nums'
        description: '2 numbers to operate with'
        required: true
      responses:
        '405':
          description: 'Invalid input'
  /results:
    get:
      tags:
        - summ
      summary: 'Get previous results'
      description: 'Multiple status values can be provided with comma separated strings'
      operationId: getResults
      responses:
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Results'
        '400':
          description: 'Invalid status value'
externalDocs:
  description: 'Find out more about Swagger'
  url: 'http://swagger.io'

components:
  schemas:
    Nums:
      type: object
      properties:
        num1:
          type: number
          format: double
          example: '12.0'
        num2:
          type: number
          format: double
          example: '1.0'
        operation:
          type: string
          description: 'Types of operations'
          enum:
            - '+'
            - '-'
            - '*'
          example: '+'
      xml:
        name: Nums
    Results:
      type: object
      properties:
        result:
          type: number
          format: double
          example: '13.0'
        input:
          type: string
          example: '12.0+1.0'