openapi: 3.0.0
info:
  title: Number Operator
  description: This is a sample server python-flask.
  contact:
    email: prokhorov.va@phystech.edu
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0-oas3
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: http://localhost:8080/server/
tags:
- name: summ
  description: Summ 2 numbers
  externalDocs:
    description: Find out more
    url: http://swagger.io
paths:
  /operate:
    post:
      tags:
      - summ
      summary: operate 2 numbers
      operationId: do_action
      requestBody:
        description: 2 numbers to operate with
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nums'
        required: true
      responses:
        "405":
          description: Invalid input
      x-openapi-router-controller: swagger_server.controllers.summ_controller
  /results:
    get:
      tags:
      - summ
      summary: Get previous results
      description: Multiple status values can be provided with comma separated strings
      operationId: get_results
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Results'
                x-content-type: application/json
        "400":
          description: Invalid status value
      x-openapi-router-controller: swagger_server.controllers.summ_controller
  /clear:
    get:
      tags:
      - clear
      summary: clear list of requests
      description: clear list of requests
      operationId: delete_results
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                example: deleted
                x-content-type: application/json
        "400":
          description: Invalid status value
      x-openapi-router-controller: swagger_server.controllers.clear_controller
components:
  schemas:
    Nums:
      type: object
      properties:
        num1:
          type: number
          format: double
          example: 12.0
        num2:
          type: number
          format: double
          example: 1.0
        operation:
          type: string
          description: Types of operations
          example: +
          enum:
          - +
          - "-"
          - '*'
      xml:
        name: Nums
    Results:
      type: object
      properties:
        result:
          type: number
          format: double
          example: 13.0
        input:
          type: string
          example: 12.0+1.0
      example:
        result: 13.0
        input: 12.0+1.0

